### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by PFindersDomain** [jonhenning/videre#2]
After installing "Videre.Core.Web.NewInstall.zip" I have added the search box to the Menu, but the search returns no results, I can not see anywhere to configure what is Indexed?

Search results pages returns error: There was an error loading your widget
no segments\* file found in Lucene.Net.Store.SimpleFSDirectory@C:\Websites\Videre\Web\App_Data\SearchIndex lockFactory=Lucene.Net.Store.NativeFSLockFactory: files:

**Comment by jonhenning** [comment]
Currently the only "out of the box" widget that supports indexing is the Blog widget.  If you open the solution up you will see under the Services folder a class called BlogSearchProvider which implements ISearchProvider.

The core will scan all assemblies looking for anything implementing this interface and add it to the Admin -> Search page, where you can control the frequency of the indexing.

Of course you can create your own widgets to do the same.

**Comment by PFindersDomain** [comment]
Thanks.
